USE [master]
GO
/****** Object:  Database [Produtos]    Script Date: 10/11/2021 15:11:54 ******/
CREATE DATABASE [Produtos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Produtos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\Produtos.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Produtos_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\Produtos_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Produtos] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Produtos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Produtos] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Produtos] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Produtos] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Produtos] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Produtos] SET ARITHABORT OFF 
GO
ALTER DATABASE [Produtos] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Produtos] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Produtos] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Produtos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Produtos] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Produtos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Produtos] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Produtos] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Produtos] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Produtos] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Produtos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Produtos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Produtos] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Produtos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Produtos] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Produtos] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Produtos] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Produtos] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Produtos] SET  MULTI_USER 
GO
ALTER DATABASE [Produtos] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Produtos] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Produtos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Produtos] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Produtos] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Produtos] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Produtos] SET QUERY_STORE = OFF
GO
USE [Produtos]
GO
/****** Object:  Table [dbo].[Produtos]    Script Date: 10/11/2021 15:11:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Produtos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](50) NOT NULL,
	[Descricao] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Produtos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Produtos] SET  READ_WRITE 
GO
