version: '3.9'

services:
  api:
    build:
      context: ./AgendamentoApi
    container_name: agendamento_api
    ports:
      - "5000:80"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=Agenda;Username=postgres;Password=1234

  postgres:
    image: postgres:13
    container_name: agendamento_db
    restart: always
    environment:
      POSTGRES_DB: Agenda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
